Gabe
ben-mulhern/dolphin-dollars pull request #10
Opened 2018-03-14 13:06 UTC by gabewilliam

Created domain files for each of the DB tables (currency, user_detail, ledger, block and block_detail)
Most are pretty much identical to their DDL counterparts

2018-03-14 13:23 UTC, ben-mulhern commented on src/main/scala/domain/Block.scala
> +                  effectiveDate: String)
We discussed Block also containing a List of BlockDetail entries.

2018-03-14 13:23 UTC, ben-mulhern commented on src/main/scala/domain/BlockDetail.scala
> +                       cashValue: Float,
I'd favour Double over Float.

2018-03-14 13:23 UTC, ben-mulhern commented on src/main/scala/domain/Ledger.scala
> +case class LedgerId(id: Option[String])
Should this be an option? When wouldn't we have a value?

2018-03-14 13:23 UTC, ben-mulhern commented on src/main/scala/domain/User.scala
> +                 password: Password,
I don't think we need the password and salt to exist in the User class - it's a security risk, we'd never want to send that data back to the browser.

2018-04-18 12:17 UTC, gabewilliam commented
Removed password & salt from user
Cash value in Block is now double
Block contains list of BlockDetails
LedgerID no longer optional field

2018-04-18 12:30 UTC, JohnHunt1990 approved these changes

2018-04-18 12:59 UTC, KarlFinn requested changes

2018-04-18 12:59 UTC, KarlFinn commented on src/main/scala/domain/Block.scala
> +case class Block (id: BlockId,
Make id an option[BlockId] to cope with uncommitted blocks

2018-04-18 12:59 UTC, KarlFinn commented on src/main/scala/domain/BlockDetail.scala
> +case class BlockDetail(id: BlockId, //'Block.scala'
id is not needed in block detail as can be derived by container block

2018-04-25 12:19 UTC, gabewilliam commented
Applied the changes Karl suggested

2018-04-25 12:21 UTC, KarlFinn approved these changes

2018-04-25 12:25 UTC, merged